spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    serialization:
      fail_on_empty_beans: false

output:
  ansi:
    enabled: ALWAYS